name: 'docker'
services:
 mysql:
  image: mysql:8.0.33
  environment:
   - MYSQL_ROOT_PASSWORD=root
  ports:
   - $MYSQL_PORT:3306
  volumes:
   - mysql-data:/var/lib/mysql/
  user: 1000:1000
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   - PMA_HOST=mysql
   - PMA_USER=root 
   - PMA_PASSWORD=root
  ports:
    - $PHPMYADMIN_PORT:80  
 mailhog:
  image: mailhog/mailhog:v1.0.1
  platform: linux/amd64
  ports:
   - 1025:1025
   - $MAILHOG_PORT:8025
 app:
  image: app
  build:
   context: .
   dockerfile: ./Dockerfiles/app.Dockerfile
   args:
    UID: $UID
  volumes:
   - $APP_VOLUMES_SRC:/var/www/html/
   - app-user-home:/home/www-data/
  env_file:
   - ./.env
  ports:
   - 5173:5173
 static:
  image: nginx:1.24.0-alpine3.17
  volumes:
   - static-public:/usr/share/nginx/html/
 proxy:
  image: proxy
  build:
   context: .
   dockerfile: ./Dockerfiles/proxy.Dockerfile
  ports:
   - $PROXY_PORT:80
  environment:
   - PHP_FPM_HOST=app
   - PUBLIC_PATH=public
   - STATIC_CONTENT_HOST=static
volumes:
  mysql-data:
  app-user-home:
  static-public:
